name: canny
path_sd_ckpt: models/control_sd15_ini.ckpt
path_config_model: models/cldm_v15.yaml
training:
  learning_rate: 1e-5
  sd_locked: True
  only_mid_control: False
logging:
  every_n_train_steps: 2000
  batch_frequency: 300
data:
  target: datasets.CannyDataset.CannyDataset
  params:
    min_resize_res: 512
    max_resize_res: 512
    crop_res: 512
    low_threshold: 100
    high_threshold: 200
    path_seed: srcs/seeds_openimage.txt
dataloader:
  batch_size: 12
  num_workers: 1 
lightning:
  precision: 32
  gpus: 1
  accumulate_grad_batches: 4

