name: dev
path_sd_ckpt: models/control_sd15_ini.ckpt
path_config_model: models/cldm_v15.yaml
training:
  learning_rate: 1e-5
  sd_locked: True
  only_mid_control: False
logging:
  every_n_train_steps: 3000
  batch_frequency: 300
data:
  target: datasets.DegradeDataset.DegradeDataset
  params:
    targets: [gray]
dataloader:
  batch_size: 1
  num_workers: 1 
lightning:
  precision: 32
  gpus: 1
  accumulate_grad_batches: 4

