name: dev
path_sd_ckpt: models/control_sd15_ini.ckpt
path_config_model: models/cldm_v15.yaml
training:
  batch_size: 1
  learning_rate: 1e-5
  sd_locked: True
  only_mid_control: False
logging:
  every_n_train_steps: 2000
  batch_frequency: 500
data:
  path: DATASET/openimage
  num_workers: 1 

lightning:
  precision: 32
  gpus: 1
  accumulate_grad_batches: 4

